/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.java;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;


public class CrudCli {

    // Crud Menu

    protected static void runCrudMenu(Scanner sc, DbMetadata dbMetadata, String tableName) {
        int crudInput = 0;
        do {
            CrudCli.displayCrudMenu(tableName);
            System.out.print("Enter your choice: ");
            crudInput = sc.nextInt();
            switch (crudInput) {
                case 1:
                    System.out.println("Selected Create.");
                    HashMap<String, String> values = new HashMap<String, String>();
                    boolean runCreate = Creator.readInsertParams(sc, dbMetadata, tableName, values);
                    if (!runCreate) {
                        System.out.println("Operation canceled.");
                        break;
                    }
                    Creator.create(dbMetadata.getCon(), tableName, values);
                    break;
                case 2:
                    System.out.println("Selected Read.");
                    HashMap<String, String> selectedCols = new HashMap<String, String>();
                    boolean getFilter = Reader.readSelectCols(sc, dbMetadata, tableName, selectedCols);
                    if (!getFilter) {
                        System.out.println("Operation canceled.");
                        break;
                    }
                    HashMap<String, String> colsFilters = new HashMap<String, String>();
                    boolean getFilterStr = Reader.readSelectFilters(sc, dbMetadata, tableName, colsFilters);
                    if (!getFilterStr) {
                        System.out.println("Operation canceled.");
                        break;
                    }
                    ArrayList<String> filterStrList = new ArrayList<String>();
                    boolean runRead = Reader.readFilterString(sc, dbMetadata, tableName, colsFilters, filterStrList);
                    if (!runRead) {
                        System.out.println("Operation canceled.");
                        break;
                    }
                    Reader.read(dbMetadata.getCon(), tableName, selectedCols.keySet(), filterStrList);
                    break;
                case 3:
                    
                    break;
                case 4:
                    
                    break;
                default:
                    break;
            }
        } while (crudInput != 0);

        System.out.println("Going back to main menu.");

    }

    protected static void displayCrudMenu(String tableName) {
        System.out.println(String.format("\nWhich operation would you like to perform on table '%s'?", tableName));
        System.out.println("\t0: BACK TO MAIN MENU");
        System.out.println("\t1: Create Item");
        System.out.println("\t2: Read Item");
        System.out.println("\t3: Update Item");
        System.out.println("\t4: Delete Item");
    }

    // Create Menu

}
