/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.util.Properties;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appLoadDbConnectionProps() {
        App app = new App();

        Properties expected = new Properties();
        expected.setProperty("db.url", "jdbc:mysql://localhost:3306/classicmodels");
        expected.setProperty("db.username", "user");
        expected.setProperty("db.password", "password");

        Properties result = app.loadDbConnectionProps();

        assertEquals(expected.getProperty("db.url"), result.getProperty("db.url"));
        // assertEquals(expected.getProperty("db.username"), result.getProperty("db.username"));
        // assertEquals(expected.getProperty("db.password"), result.getProperty("db.password"));
    }

    @Test void appGetDbConnection() {
        App app = new App();

        Connection result = app.getDbConnection();

        assertNotNull(result, "connection to database failed");

        app.closeDbConnection(result);
    }
}
