/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;
import java.util.Properties;

class DBConnectorTest {

    @Test void loadDbConnectionProps() {
        DbConnector dbCon = new DbConnector();

        Properties expected = new Properties();
        expected.setProperty("db.vendor", "mysql");
        expected.setProperty("db.ip", "localhost");
        expected.setProperty("db.port", "3306");
        expected.setProperty("db.name", "classicmodels");
        expected.setProperty("db.username", "user");
        expected.setProperty("db.password", "password");

        Properties result = dbCon.loadDbConnectionProps();

        assertEquals(expected.getProperty("db.vendor"), result.getProperty("db.vendor"));
        assertEquals(expected.getProperty("db.ip"), result.getProperty("db.ip"));
        assertEquals(expected.getProperty("db.port"), result.getProperty("db.port"));
        assertEquals(expected.getProperty("db.name"), result.getProperty("db.name"));
        // assertEquals(expected.getProperty("db.username"), result.getProperty("db.username"));
        // assertEquals(expected.getProperty("db.password"), result.getProperty("db.password"));
    }

    @Test void getDbConnection() throws SQLException {
        DbConnector dbCon = new DbConnector();

        dbCon.setDbConnection();

        assertNotNull(dbCon.getCon(), "connection to database failed");

        dbCon.closeDbConnection();

        assertTrue(dbCon.getCon().isClosed());
    }
}
