/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;

class DbMetadataTest {

    @Test void test() {

    }
}
